<?php

namespace AppBundle\Repository;

/**
 * CVExperienceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CVExperienceRepository extends \Doctrine\ORM\EntityRepository
{
}
