<?php

namespace AppBundle\Repository;

/**
 * CVFormationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RealisationsRepository extends \Doctrine\ORM\EntityRepository
{
}
